#ifndef __TUPLECALLBACK_H__
#define __TUPLECALLBACK_H__
#include<Variable.h>
#include<Relation.h>
#include<Domain.h>

class TupleCallback{
	public:
	virtual void execute(map<Variable*,vector<int>*> & tuple)
	{
		deallocate(tuple);	
	};
	virtual void executeTrue()
	{
	};
	virtual void executeFalse()
	{
	};
	protected:
	virtual void deallocate(map<Variable *,vector<int>*> & tuple)
	{
		map<Variable*,vector<int>*>::iterator iter;
		for(iter=tuple.begin();iter!=tuple.end();++iter){
			delete ((iter)->second);
		}
	};

};
/*
 *
 * 
 * A typical callback function class (to be generated by a query-language
 * compiler).
 * class TupleCallbackAquery{
 * 	public:
 * 	   net * v1;
 * 	   net * v2;
 * 	   net * v3;
 * 	   virtual void operator(map<Variable *,vector<int>*> &tuple){
 *		// assign the relevant values to the member variables
 *		//For each free variable get its values.
 *              // if the entry does not exist go through the entire 
 *              // range of values that it can take
 *              // the compiler should be aware of the variables free in
 *              // the expression 
 *
 *               // The action body should be pasted here.
 *
 * 	   };
 * };
 */


#endif
